name: Merge-upstream

on:
  schedule:
    - cron: 55 14 * * *
#  push:
#    branches: 
#    - master
  watch:
    types: started

jobs:

  merge:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:

    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: master
        fetch-depth: 0
        lfs: true

    - name: Set git identity
      run : |
        git config --global user.email "KFER.Mercer@gmail.com"
        git config --global user.name "KFERMercer"

    - name: Load upstream commits
      run: git pull https://github.com/CareyWang/sub-web.git --no-edit

    - name: Push Commits 
      run: git push origin master